In [9]:
#longest string length
lst = ['johnDoe1','janeDoe']

max = 0
for i in range(len(lst)):
    if(len(lst[i])>max):
        max = len(lst[i])
        maxStr = lst[i]
print(maxStr)

johnDoe1


In [4]:
#write a sums of cur and previous without using function #
cur = 1
nxt = 1
print(cur)
print(nxt)
for i in range(1,10):
    sum = cur + nxt
    print(sum)
    cur = nxt
    nxt = sum


1
1
2
3
5
8
13
21
34
55
89


In [6]:
#write a factorial using function
def fact(x):
    if x==1:
        return x
    else:
        return x * fact(x-1)
fact(5)

120

In [16]:
#write a factorial using function
def fact(x):
    if x<2:
        return x
    else:
        return fact(x-1) + fact(x-2)
fact(7)

13

In [3]:
dict = {
    "name": "Nami San",
    "gender": "Female"
    }

In [5]:
dict['gender']

'Female'

In [52]:
li = ['1','2','3','4','5']
print(li.sort())

None


In [49]:
tl = 5
ip = 5
ip2 = 5
print(' '* (5) +'  *'+ ' ' +' '*5)
for x in range(3):
    ip = 5
    for x in range(2, ip+1):
        print(' '* (ip) +' *'*x+ ' ' +' '* (ip))
        ip-=1

        

       *      
      * *      
     * * *     
    * * * *    
   * * * * *   
      * *      
     * * *     
    * * * *    
   * * * * *   
      * *      
     * * *     
    * * * *    
   * * * * *   
      * *
      * *
      * *
      * *


In [56]:
a = 'nevs'
def fun1():
    print('Hello ',a)
    
fun1()

Hello  nevs


In [57]:
x = lambda x: x+12
x(12)

24

In [58]:
fn = lambda a,b: a+b
fn(2,4)

6

In [69]:
from functools import *

li = [1,2,2,4,1,2]
f2 = reduce(lambda a,b:a+b,li)
print(f2)
li = [[1,2],[2,4],[1,2]]
f2 = list(map(lambda a,b:a[0]+b[1],li,li))
print(f2)

12
[3, 6, 3]


In [75]:
class a:
    x = 10
    def __init__(self, x):
        self.x = x
        
obj = a(12)
print(obj.x)
print(a.x)

12
10


In [12]:
#Regular Expression
import re

str = "Steven asks nothing"

re.findall('\W',str)

[' ', ' ']

In [13]:
re.sub(r'[a-z]','','4g5hj6')

'456'

In [16]:
date = '2020-02-03'
re.sub(r'(\d{4})-(\d{2})-(\d{2})',r'\2/\3/\1',date)

'02/03/2020'

In [44]:
# Write a Python program to check that a string contains only a certain set of characters (in this case a-z, A-Z and 0-9)
import re
str1 = 'sas129nk..saZZA'
re.findall(r'[^a-zA-Z0-9]',str1)

['.', '.']

In [48]:
def checkValid(str, b=True):
    if(b):
        if(len(re.findall(r'\w',str))==0):
            print("Valid String")
        else:
            print("Invalid String")
    else:
        if(len(re.findall(r'\W',str))==0):
            print("Valid String")
        else:
            print("Invalid String")

checkValid('sas129nk..saZZA',False)
checkValid('sas129nksaZZA',False)
checkValid('@^.^@')

Invalid String
Valid String
Valid String


In [63]:
#Write a python program that matches a string that has an a followed by zero or more b's
def checkValid(str):
    if len(re.findall(r'bbb$',str))>0:
        print('String contains 3 characters of "b"')
    else:
        print('String does not contains trailing of character "b"')
    
checkValid('asasdbb')
checkValid('asasdbbb')
checkValid('asasdb')


String does not contains trailing of character "b"
String contains trailing of character "b"
String does not contains trailing of character "b"


In [67]:
'{0:.2}'.format(1/3)

'0.33'

In [2]:
for i in range(5):
    print((str(i)+ ' ') * i) 


1 
2 2 
3 3 3 
4 4 4 4 


In [7]:
for i in range(5):
    print('')
    for j in range(i+1):
        print(j+1,end=' ') 


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 

In [10]:
n = 5
for i in range(n):
    print('*' * (n-i)) 

*****
****
***
**
*


In [43]:
def HCF(args=[]):
    min = args[0]
    for i in range(len(args)):
        if(min > args[i]):
            min = args[i]
    #print(min)
    for i in range(min,2,-1):
        flag = True
        for n in args:
            if(n%i!=0):
                #print(n,i)
                flag = False
                break
        if(flag):
            return i
    return "Not Found"

i = HCF([12,72,68,56])
print(i)

4


In [8]:
ip = 5
for x in range(1, ip+1):
    print(' '* (ip) +' *'*x+ ' ' +' '* (ip))
    ip-=1
ip2 = 5
for x in range(1, ip2+1//2):
    print(' '+' '*(ip2//2)+ ' '+ ' *'*(ip2//2))

      *      
     * *     
    * * *    
   * * * *   
  * * * * *  
     * *
     * *
     * *
     * *


In [17]:
y = 1
for i in range(1,10):
    print('')
    for j in range(1,10):
        if(i<y or j<y):
            print('*',end = ' ')
            
    y += 1



* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * * * 
* * * * * * * * 

In [116]:
arr = {0:'WS',1:'WS',12:'WS','6':'WS','7':'WS','2':'MS','5':'MS','8':'MS',11:'MS','3':'AS','4':'AS','9':'AS','10':'AS'}

print(arr.get(1))
def oppositeSeat(num):
    #opp seat
    if(num%12==0):
        print("Opposite seat no. is",((int(num/12)-1)*12)+1)
        print("Type of seat no.",((int(num/12)-1)*12)+1,"is the Window Seat")
        return
    oppSeat = 12*(int(num/12)+1)+1 - (num%12)
    print("Opposite seat of",num,"is ",oppSeat)
    #type seat
    numTemp = (oppSeat%12)
    print(numTemp)
    print("Type of seat no. ",oppSeat," is the",arr.get(numTemp))
    
    
oppositeSeat(47)

WS
Opposite seat of 47 is  38
2
Type of seat no.  38  is the None


In [49]:
num = 1
oppSeat = 12*(int(num/12)+1)+1 - (num%12)
print(oppSeat)

12


In [147]:
import random, string

def gen():
    len1 = random.randint(8,15)
    pwd = ''
    arr = []
    for i in range(len1):
        n = random.randint(1,3)
        if(n==1):
            arr.append(random.choice(string.ascii_letters))
        elif(n==2):
            arr.append(random.choice('@%#$*!@&*!'))
        else:
            arr.append(random.choice('1234567890'))
    
    random.shuffle(arr)
    pwd = ''.join(arr)
    print(pwd)
gen()

cytB!Pg309!@


In [149]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [160]:
import re

str = '2 m 32a w 7 1 a'
char = ''
num = ''
for p in str:
    if p == ' ':
        continue
    elif re.search("[A-Za-z]",p):
        char += p
        continue
    elif re.search("[0-9]",p):
        num += p
        continue
    else:
        print('???.. ignore')

print(char)
print(num)

mawa
23271


In [154]:
for p in str:
    print(p)

2
 
m
 
3
 
w
 
7
 
1
 
a


In [12]:
d = {9:[2,1,3,4,5,6,7,8]}

d[9].sort()
arr = d[9]
arr2 = []
for x in arr:
    if(x<9):
        arr2.append(x)

for i in arr2:
    print(i)
    
    sum(0,)

1
2
3
4
5
6
7
8


In [17]:
import tkinter as tk
window = tk.Tk()
greeting = tk.Label(text="Red",fg="White",bg="Red",width="10",height="10")
#run on shell

*String processing*

In [14]:
print('abc'.isalpha())
print('abc'.isdecimal())
print('abc'.isalnum())
print('abc'.isnumeric())
print('abc'.islower())
print('abc'.isupper())
print('cabc'.strip('c'))
print('abc'.rfind('c'))
print('abc'.partition('b'))

True
False
True
False
True
False
ab
2
('a', 'b', 'c')


List

In [34]:
li = list([1,2,3,4])
li.append(1)
li

[1, 2, 3, 4, 1]

In [33]:
for i in enumerate(li):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 1)


In [43]:
print(any([1,2,0]))
print(all([1,2,0,False]))

True
False


In [48]:
ml = [ pow(i,2) for i in li]
ml

[1, 4, 9, 16, 1]

In [62]:
dict = {'1':'abc',2:'bcd'}
x = list(dict.values())
x

['abc', 'bcd']

In [63]:
dict

{'1': 'abc', 2: 'bcd'}

In [3]:
import numpy as np
n = np.arange(15).reshape(5, 3)
n.dtype

dtype('int32')

In [9]:
a = np.arange(9).reshape(3, 3)
b = np.array([10,10,10,10,10,10,10,10,10]).reshape(3, 3)
c = abs(a-b)
c

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [37]:
r = np.asarray([2,3,1,6,3,6,2,3,4])
np.searchsorted(r,[1,2])

array([0, 3], dtype=int32)

In [12]:
d = a.copy()

In [13]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
print(d,d.data, d.dtype,d.shape, d.base)

[[0 1 2]
 [3 4 5]
 [6 7 8]] <memory at 0x0AB22E40> int32 (3, 3) None


In [19]:
d.view()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.sortedsearch(d,2)

AttributeError: module 'numpy' has no attribute 'sortedsearch'

# Classes and Method

In [42]:
class A:
    def _init_(self):
        pass
    
    def super1(self):
        print('Base Class')
    
class B(A):
    def _init_(self):
        pass
    
    def super2(self):
        print('Drived Class')
        super().super1()
        
a = B()
a.super2()

Drived Class
Base Class


In [43]:
import pandas as pd

In [47]:
data = {'name':['steve','steve2','steve3','steve4','steve5'],'num':[1,2,4,5,2]}

df = pd.DataFrame(data)
df

name  num
0   steve    1
1  steve2    2
2  steve3    4
3  steve4    5
4  steve5    2